### ISSUE TITLE
when running example 1,3,5, error occured. Error using calllib. The pointer type must match the data type

### ISSUE THREAD

**Issue by laolihaile** [zishun/geodesic_matlab#3]
Error using calllib. 
The pointer type must match the data type

Error geodesic_distance_and_source (line 19)
    [num_vertices, d, s] = calllib(geodesic_library, 'distance_and_source_for_all_vertices', algorithm.id, tmp, tmp1);

Error example3 (line 30)
[source_ids, distances] = geodesic_distance_and_source(algorithm);     %for every vertex, figure out which source it belongs to

Could you please help me solve this problem? Thank you~

**Comment by zishun** [comment]
Which version of Matlab is used? When I was using R2019a, [line 17](https://github.com/zishun/geodesic_matlab/blob/master/matlab/geodesic_distance_and_source.m#L17) should be replaced with line 18 in [matlab/geodesic_distance_and_source.m](https://github.com/zishun/geodesic_matlab/blob/master/matlab/geodesic_distance_and_source.m). Maybe you can try line 17 instead of line 18.

If it does not work, maybe you can update your Matlab or revert the changes [here](https://github.com/zishun/geodesic_matlab/commit/dd9d83491242d2c15cf745f8ed65d90a0542c258#diff-b83c93a02d93a148dd68d2175b3099af).

**Comment by laolihaile** [comment]
I use R2019b. I replce line 17 with line 18, but it doesn't work, the error still exists

**Comment by laolihaile** [comment]
OH ! IT WORKS NOW! I just replaced it BUT I didn't save it. THANK YOU VERY MUCH!

**Comment by zishun** [comment]
No problem! I will double check when I have access to R2019b or newer versions.
